---
layout:	single
title: "[Java] 024. 예외처리(Exception)"
excerpt: "예외처리(Exception)에 대해 알아보자"
categories: Java
tag: [STUDY, Java]
toc: true
toc_sticky: true
author_profile: false
sidebar:
    nav: "docs"
search: true
permalink: categories/java/024-Exception
# last_modified_at:

---

# 예외처리(Exception)

```java
import java.util.InputMismatchException;
import java.util.Scanner;

public class Exception {
	
	/*
	 * # 예외 (Exception)
	 * 
	 * 	- 우리가 에러라고 생각했던 빨간 글씨들을 사실 예외라고 부른다. (배열크기가 100인데 100번에 접근하려고 했던 것 등..)
	 * 	- 자바의 문법을 틀리는 것은 예외가 아니라 컴파일 에러(문법 오류)라고 부른다.
	 * 	- 프로그래머가 발생할 예외를 미리 예측하고 대비해두는 것을 예외 처리라고 부른다.
	 * 	- 예외 처리의 기본 동작은 프로그램 강제 종료이다.
	 * 
	 * # 예외 처리
	 * 
	 * 	- 예외가 발생할 가능성이 있는 코드를 try문 내부에 포함시킨다.
	 * 	- try문 내부에서 예외가 발생하지 않으면 모두 정상 실행된다.
	 * 	- try문 내부에서 예외가 발생하는 즉시 try문 실행을 중단하고,
	 * 	  발생한 예외에 해당하는 catch문으로 넘어가게 된다.
	 * 	- 예외 발생시 catch문에 발생한 예외에 대한 정보를 담고 있는 인스턴스가 전달된다.
	 * 	- catch문은 중첩이 가능하다.
	 * 	- 예외 발생 여부와 관계없이 무조건 실행하고 싶은 코드는 finally에 작성한다.
	 */
	
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		int[] arr = new int[10];

		try {
			System.out.print("반드시 숫자만 입력해주세요 >> ");
			int num = sc.nextInt();
			System.out.println("입력값: " + num);

			// System.out.println(arr[10]);
			System.out.println(arr[(int) (Math.random() * 20)]);
			int a = 10 / 0;
			
			
		} catch (InputMismatchException e) {
			System.err.println("내가 숫자만 입력하라고 했을텐데?");
			System.out.println("## 에러정보 ##");
			System.out.println("Error Message: " + e.getMessage());
			System.out.println("Stack Trace: " + e.getStackTrace());
			
			e.printStackTrace();
			
			// e.printStackTrace(); 와 동일
//			StackTraceElement[] stack_traces = e.getStackTrace();
//			for (int i = 0; i < stack_traces.length; ++i) {
//				System.out.println(stack_traces[i]);
//			}

		} catch (ArrayIndexOutOfBoundsException e) { // 지역 변수라서 변수명 같은 걸로 가능
			System.out.println("잘못된 인덱스 접근입니다.");
		} catch (ArithmeticException e) { // 지역 변수라서 변수명 같은 걸로 가능
			System.out.println("0으로 나누시면 안 됩니다.");
		} catch (Exception e) {
			// Exception은 모든 Exception의 부모여서 얘를 넘어갈 수 없다.
			// 그래서 제일 위에 적으면 밑에 있는 예외들에서 오류가 발생한다.
			// 맨 밑에 적어서 위의 예외외의 예외들을 처리해준다.
			// catch문의 순서가 중요하다.
			System.out.println("위의 경우를 제외한 모든 예외를 처리할 수 있음.");
		} finally {
			System.out.println("예외 발생 여부와 관계없이 무조건 실행하고 싶은 코드는 finally에 작성한다.");
			System.out.println(" /)/)");
			System.out.println("(  ..)");
			System.out.println("(  >$");
		}

		System.out.println("프로그램을 계속 실행합니다...");
	}
}

```

# Throw

```java
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.InputMismatchException;

public class Throw {
	
	/*
	 * # throw
	 * 
	 * 	- 즉시 원하는 예외를 발생시킨다. (throw는 catch를 찾아서 간다.)
	 * 
	 * # throws
	 * 
	 * 	- 해당 메서드에서 발생하는 예외에 대한 처리를 메서드를 호출한 곳으로 미룰 수 있다.
	 * 
	 * # 꼭 처리하지 않아도 되는 예외
	 * 
	 * 	- RuntimeException 클래스를 상속받은 예외들은 반드시 처리하지 않아도 된다.
	 * 	- 예외 처리를 하지 않아도 컴파일 에러(빨간줄)는 발생하지 않는다.
	 * 
	 * # 필수로 처리해야 하는 예외
	 * 
	 * 	- Exception 클래스를 상속받은 예외들은 처리하지 않으면 컴파일이 불가능하다.
	 * 	- 어딘가에서는 반드시 try-catch로 처리되어야 컴파일을 진행할 수 있다.
	 * 
	 */
	
	/*
	// 꼭 처리하지 않아도 되는 예외들
	public static int awesomeMethod() {
		
		switch ((int) (Math.random() * 10)) {
		case 0:
			throw new ArithmeticException("0이 나왔네요");
		case 1:
			throw new IndexOutOfBoundsException("1이 나왔네요");
		case 2:
			throw new InputMismatchException("2가 나왔네요");
		default:
			throw new IllegalArgumentException();
		}
	}
	*/
	
	// throws
	// 해당 메서드에서 발생하는 예외에 대한 처리를 메서드를 호출한 곳으로 미룰 수 있다.
	// awesomeMethod2()는 FileNotFoundException, IOException 가 발생할 수 있다는 걸 알려준다.
	public static int awesomeMethod2() throws FileNotFoundException, IOException {
		switch ((int) (Math.random() * 10)) {
		case 0:
			return 0;
		case 1:
			throw new FileNotFoundException("1이 나왔네요");
		case 2:
			throw new IOException("2가 나왔네요");
		default:
			throw new IllegalArgumentException();
		}
	}
	
	public static int awesomeMethod() {
		try {
			switch ((int) (Math.random() * 10)) {
			case 0:
				return 0;
			case 1:
				throw new FileNotFoundException("1이 나왔네요");
			case 2:
				throw new IOException("2가 나왔네요");
			default:
				throw new IllegalArgumentException();
			}
		} catch (FileNotFoundException e) {
			return -1;
		} catch (IOException e) {
			return -2;
		}
	}

	public static void main(String[] args) {
		
		try {
			awesomeMethod2();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		
		// throw new InputMismatchException("아무튼 잘못됐음");
		
		/*
		// # throw 예제
		try {
			throw new InputMismatchException("아무튼 잘못됐음");
		} catch (InputMismatchException e) {
			System.out.println(e.getMessage());
			// 예외처리 기본동작
			e.printStackTrace(); // 1. 오류메시지 출력
			System.exit(0); // 2. 프로그램 종료
		}
		 */
		
	}
	
//	public static void main(String[] args) {
//		
//		try {
//			throw new FileNotFoundException(); // IOException를 상속받아서 밑 catch문 가능
//			// throw new IOException("내가 만든 IOException");
//		} catch (IOException e) {
//			System.out.println("IOException 처리");
//		}
//		
//		// throw new InputMismatchException("아무튼 잘못됐음");
//		
//		/*
//		// # throw 예제
//		try {
//			throw new InputMismatchException("아무튼 잘못됐음");
//		} catch (InputMismatchException e) {
//			System.out.println(e.getMessage());
//			// 예외처리 기본동작
//			e.printStackTrace(); // 1. 오류메시지 출력
//			System.exit(0); // 2. 프로그램 종료
//		}
//		*/
//		
//	}
}

```

# CustomException

```java

public class CustomException {
	
	/*
	 * # 원하는 예외 직접 만들어서 사용하기
	 * 
	 * 	- Exception을 상속 받으면 반드시 처리해야 하는 예외
	 * 	- RuntimeException을 상속받으면 처리하지 않아도 되는 예외
	 */
	
	public static void main(String[] args) {
		// Object : 모든 타입의 부모
		Object obj1 = 10;
		Object obj2 = "ABCDEFG";
		Object obj3  = new Apple();
		
		try {
			test2(new Apple());
		} catch (NotSwimmerException e1) {
			System.out.println("Swimmer 인터페이스가 아님");
		}
		
		try {
			test(213);
		} catch (NotEvenException e) {
			e.printStackTrace();
		}
	}

	// Object : 모든 타입의 부모
	public static void test2(Object obj) throws NotSwimmerException {
		if (obj instanceof Swimmer) { // obj가 Swimmer의 instance가 맞는지 확인
			((Swimmer) obj).swim(); // 다운캐스팅해서 swim()을 실행
		} else {
			throw new NotSwimmerException(); // 아니라면 예외발생
		}
	}

	public static boolean test(int num) throws NotEvenException {
		if (num % 2 == 0) {
			return true;
		} else {
			throw new NotEvenException();
		}
	}
}

class NotSwimmerException extends Exception {
	public NotSwimmerException() {
		super("수영을 못하는 객체");
	}
}

// 짝수가 아니라면 발생하는 예외
class NotEvenException extends Exception {

	public NotEvenException() {
		super("홀수입니다."); // new Exception()
	}

	// 생성자 오버로딩, 메시지 전달
	public NotEvenException(String message) {
		super(message);
	}
}

```

